### ISSUE TITLE
Error controlling media: `Can't use DBus for media` and `Pulseaudio is not installed`

### ISSUE THREAD

**Issue by giggio** [bkbilly/lnxlink#115]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

Ubuntu 24.04

### Which version of LNXLink has the issue?

2024.7.0

### Describe the problem

I can't control media.

### Configuration

```yaml
mqtt:
  prefix: lnxlink
  clientId: rog2
  server: redacted
  port: redacted
  auth:
    user: redacted
    pass: redacted
    tls: true
    keyfile: ''
    certfile: ''
    ca_certs: ''
  discovery:
    enabled: true
  lwt:
    enabled: true
    qos: 1
    retain: false
update_interval: 5
hass_url: null
hass_api: null
modules:
- audio_select
- camera_used
- cpu
- disk_usage
- display_env
- gpu
- idle
- inference_time
- media
- memory
- network
- required_restart
- screen_onoff
- speaker_used
- suspend
- sys_updates
- temperature
- wifi
- update
custom_modules: null
exclude:
- bash
- battery
- boot_select
- brightness
- fullscreen
- gpio
- ir_remote
- keep_alive
- keyboard_hotkeys
- mouse
- notify
- power_profile
- screenshot
- send_keys
- speech_recognition
- statistics
- systemd
- webcam
- xdg_open
settings:
  systemd: null
  gpio:
    inputs: null
    outputs: null
  hotkeys: null
  disk_usage:
    include_disks: []
    exclude_disks: []
  statistics: null
  bash:
    allow_any_command: false
    expose: null
  mounts:
    autocheck: false
    directories: []
  ir_remote:
    receiver: null
    transmitter: null
    buttons: []
```

### Logs

```bash
Jul 08 16:01:32 rog2 lnxlink[127495]: ERROR:lnxlink:Pulseaudio is not installed on your system: 'NoneType' object has no attribute 'Pulse'
Jul 08 16:01:32 rog2 lnxlink[127495]: WARNING:dbus_idle:Could not load DBusIdleMonitor
Jul 08 16:01:32 rog2 lnxlink[127495]: WARNING:dbus_idle:Could not load XprintidleIdleMonitor
Jul 08 16:01:32 rog2 lnxlink[127495]: WARNING:dbus_idle:Could not load X11IdleMonitor
Jul 08 16:01:32 rog2 lnxlink[127495]: WARNING:dbus_idle:Could not load WindowsIdleMonitor
Jul 08 16:01:32 rog2 lnxlink[127495]: ERROR:lnxlink:Can't use DBus for media
Jul 08 16:01:32 rog2 lnxlink[127495]: ERROR:lnxlink:Error with addon Media Info: 'NoneType' object has no attribute 'Mixer', Traceback (most recent call last):
Jul 08 16:01:32 rog2 lnxlink[127495]:   File "/home/user/.local/share/pipx/venvs/lnxlink/lib/python3.11/site-packages/lnxlink/__main__.py", line 121, in run_module
Jul 08 16:01:32 rog2 lnxlink[127495]:     pub_data = method()
Jul 08 16:01:32 rog2 lnxlink[127495]:                ^^^^^^^^
Jul 08 16:01:32 rog2 lnxlink[127495]:   File "/home/user/.local/share/pipx/venvs/lnxlink/lib/python3.11/site-packages/lnxlink/modules/media.py", line 100, in get_info
Jul 08 16:01:32 rog2 lnxlink[127495]:     "volume": self._get_volume(),
Jul 08 16:01:32 rog2 lnxlink[127495]:               ^^^^^^^^^^^^^^^^^^
Jul 08 16:01:32 rog2 lnxlink[127495]:   File "/home/user/.local/share/pipx/venvs/lnxlink/lib/python3.11/site-packages/lnxlink/modules/media.py", line 136, in _get_volume
Jul 08 16:01:32 rog2 lnxlink[127495]:     mixer = self.lib["alsaaudio"].Mixer()
Jul 08 16:01:32 rog2 lnxlink[127495]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 08 16:01:32 rog2 lnxlink[127495]: AttributeError: 'NoneType' object has no attribute 'Mixer'
```

**Comment by bkbilly** [comment]
I am a bit confused of your logs and the configuration because you have ignored media and it shows up in the logs. Also it would be useful to have the full logs from when service starts.

For graphical interfaces, the `display_env` module is required for the other modules to work.
Also make sure the dependencies are installed:
```bash
sudo apt install patchelf meson libdbus-glib-1-dev libglib2.0-dev libcairo2-dev libgirepository1.0-dev
sudo apt install libasound2-dev upower xdotool xdg-utils python3-pyaudio portaudio19-dev
```

In case this doesn't work, you could try installing the python dependencies manually like so:
```bash
/home/user/.local/share/pipx/venvs/lnxlink/bin/python -m pip install pyalsaaudio
```

**Comment by giggio** [comment]
Running the 2 `apt install` showed all those packages were already installed.

Running the `pip install` returned an error:

```
Collecting pyalsaaudio
  Using cached pyalsaaudio-0.11.0.tar.gz (311 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyalsaaudio
  Building wheel for pyalsaaudio (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pyalsaaudio (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'alsaaudio' extension
      creating build
      creating build/temp.linux-x86_64-cpython-311
      gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/nix/store/5xynf9c9ml7d97q70kpq9rpqqmx13xl8-libxcrypt-4.4.36/include -fPIC -I/home/user/.local/share/pipx/venvs/lnxlink/include -I/nix/store/7hnr99nxrd2aw6lghybqdmkckq60j6l9-python3-3.11.9/include/python3.11 -c alsaaudio.c -o build/temp.linux-x86_64-cpython-311/alsaaudio.o
      alsaaudio.c:28:10: fatal error: alsa/asoundlib.h: No such file or directory
         28 | #include <alsa/asoundlib.h>
            |          ^~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/home/user/.nix-profile/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyalsaaudio
Failed to build pyalsaaudio
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pyalsaaudio)
```

I noticed an error on the `journalctl` logs, which indicates a similar problem for installing `pyalsaaudio`:


```
Jul 08 20:11:16 rog2 systemd[4567]: Started lnxlink.service - LNXlink.
Jul 08 20:11:16 rog2 lnxlink[191541]: INFO:lnxlink:LNXlink 2024.7.0, Python 3.11.9
Jul 08 20:11:16 rog2 lnxlink[191541]: ERROR:lnxlink:Can't import package dbus-python: libsystemd.so.0: cannot open shared object file: No such file or directory
Jul 08 20:11:16 rog2 lnxlink[191541]: ERROR:lnxlink:Can't use DBus for system monitor
Jul 08 20:11:16 rog2 lnxlink[191541]: ERROR:lnxlink:Can't import package pulsectl: libpulse.so.0: cannot open shared object file: No such file or directory
Jul 08 20:11:16 rog2 lnxlink[191541]: ERROR:lnxlink:Pulseaudio is not installed on your system: 'NoneType' object has no attribute 'Pulse'
Jul 08 20:11:16 rog2 lnxlink[191541]: ERROR:lnxlink:Can't import package dbus-python: libsystemd.so.0: cannot open shared object file: No such file or directory
Jul 08 20:11:16 rog2 lnxlink[191541]: INFO:lnxlink:Installing 'pyalsaaudio>=0.9.2'...
Jul 08 20:11:17 rog2 lnxlink[191541]: ERROR:lnxlink:Can't install package pyalsaaudio
Jul 08 20:11:17 rog2 lnxlink[191541]: ERROR:lnxlink:Can't import package mpris2: libsystemd.so.0: cannot open shared object file: No such file or directory
```

I did have excluded and included modules, I fixed that, I'll update the issue description.

**Comment by giggio** [comment]
Ok, it is related to nixpkgs. I'm on Ubuntu but using nixpkgs for pretty much everything. After changing the path to prefer the system installed Python the pip install command worked. I'll figure out what is happening and post an update.

**Comment by giggio** [comment]
I'm closing the issue, it was entirely related to Nix and Nixpkgs.
I completely removed Python from my home-manager installation, but it's dependencies were still a problem when building native python dependencies. Only when I completely removed any reference to Nix from the path did the project build and work.
I'm not sure why this is hapening, I haven't had similar problems with other languages, but I do know these things can happen with Nix.
The thing that helped me was your tip to use `python -m pip install` directly, which allowed me to evolve my investigation. Thanks for that.

**Comment by bkbilly** [comment]
I am not familiar with Nix Package Manager, but I am happy that you finally managed to get it running.
