### ISSUE TITLE
Home Assistant/MQTT not receiving any data (first time setup)

### ISSUE THREAD

**Issue by Iceman248** [bkbilly/lnxlink#17]
Default config, get this when I try to manually run after didn't work with the stock procedure. The last error repeats over and over.

```
Successfully loaded addon: cpu
Error with module: media
Traceback (most recent call last):
  File "/opt/lnxlink/modules/__init__.py", line 15, in <module>
    addons = getattr(import_module(f"{__name__}.{module_name}"), 'Addon')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/lnxlink/modules/media.py", line 4, in <module>
    import alsaaudio
ModuleNotFoundError: No module named 'alsaaudio'
Error with module: media
Traceback (most recent call last):
  File "/opt/lnxlink/modules/__init__.py", line 15, in <module>
    addons = getattr(import_module(f"{__name__}.{module_name}"), 'Addon')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/lnxlink/modules/media.py", line 4, in <module>
    import alsaaudio
ModuleNotFoundError: No module named 'alsaaudio'
Error with module: media
Traceback (most recent call last):
  File "/opt/lnxlink/modules/__init__.py", line 15, in <module>
    addons = getattr(import_module(f"{__name__}.{module_name}"), 'Addon')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/lnxlink/modules/media.py", line 4, in <module>
    import alsaaudio
ModuleNotFoundError: No module named 'alsaaudio'
Error with module: media
Traceback (most recent call last):
  File "/opt/lnxlink/modules/__init__.py", line 15, in <module>
    addons = getattr(import_module(f"{__name__}.{module_name}"), 'Addon')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/lnxlink/modules/media.py", line 4, in <module>
    import alsaaudio
ModuleNotFoundError: No module named 'alsaaudio'
Error with module: media
Traceback (most recent call last):
  File "/opt/lnxlink/modules/__init__.py", line 15, in <module>
    addons = getattr(import_module(f"{__name__}.{module_name}"), 'Addon')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/lnxlink/modules/media.py", line 4, in <module>
    import alsaaudio
ModuleNotFoundError: No module named 'alsaaudio'
Error with module: media
Traceback (most recent call last):
  File "/opt/lnxlink/modules/__init__.py", line 15, in <module>
    addons = getattr(import_module(f"{__name__}.{module_name}"), 'Addon')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/lnxlink/modules/media.py", line 4, in <module>
    import alsaaudio
ModuleNotFoundError: No module named 'alsaaudio'
Error with module: media
Traceback (most recent call last):
  File "/opt/lnxlink/modules/__init__.py", line 15, in <module>
    addons = getattr(import_module(f"{__name__}.{module_name}"), 'Addon')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/lnxlink/modules/media.py", line 4, in <module>
    import alsaaudio
ModuleNotFoundError: No module named 'alsaaudio'
Error with module: media
Traceback (most recent call last):
  File "/opt/lnxlink/modules/__init__.py", line 15, in <module>
    addons = getattr(import_module(f"{__name__}.{module_name}"), 'Addon')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/lnxlink/modules/media.py", line 4, in <module>
    import alsaaudio
ModuleNotFoundError: No module named 'alsaaudio'
Error with module: media
Traceback (most recent call last):
  File "/opt/lnxlink/modules/__init__.py", line 15, in <module>
    addons = getattr(import_module(f"{__name__}.{module_name}"), 'Addon')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/lnxlink/modules/media.py", line 4, in <module>
    import alsaaudio
ModuleNotFoundError: No module named 'alsaaudio'
Error with module: media
Traceback (most recent call last):
  File "/opt/lnxlink/modules/__init__.py", line 15, in <module>
    addons = getattr(import_module(f"{__name__}.{module_name}"), 'Addon')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/lnxlink/modules/media.py", line 4, in <module>
    import alsaaudio
ModuleNotFoundError: No module named 'alsaaudio'
Error with module: media
Traceback (most recent call last):
  File "/opt/lnxlink/modules/__init__.py", line 15, in <module>
    addons = getattr(import_module(f"{__name__}.{module_name}"), 'Addon')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/lnxlink/modules/media.py", line 4, in <module>
    import alsaaudio
ModuleNotFoundError: No module named 'alsaaudio'
Successfully loaded addon: memory
Successfully loaded addon: network
Successfully loaded addon: notify
Successfully loaded addon: restart
Successfully loaded addon: send_keys
Successfully loaded addon: shutdown
LNXLink started
Connected to MQTT with code 0
Exception in thread Thread-1 (_thread_main):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
Can't load addon: media
  File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
Traceback (most recent call last):
  File "/opt/lnxlink/run.py", line 44, in monitor_run
    addon = self.Addons[service]
KeyError: 'media'
    self.loop_forever(retry_first_connection=True)
  File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 3039, in _packet_handle
    return self._handle_connack()
  File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 3138, in _handle_connack
    on_connect(
  File "/opt/lnxlink/run.py", line 95, in on_connect
    self.setup_discovery()
  File "/opt/lnxlink/run.py", line 147, in setup_discovery
    addon = self.Addons[service]
KeyError: 'media'
Can't load addon: media
Traceback (most recent call last):
  File "/opt/lnxlink/run.py", line 44, in monitor_run
    addon = self.Addons[service]
KeyError: 'media'
Can't load addon: media
Traceback (most recent call last):
  File "/opt/lnxlink/run.py", line 44, in monitor_run
    addon = self.Addons[service]
```

**Comment by bkbilly** [comment]
Seems that you are missing a python package.
You can install it like this:
```sudo apt python3-alsaaudio```

if it doesn't work, please send me your OS version.

**Comment by Iceman248** [comment]
No matter what I use, it can't find the required packages to install that. EndeavourOS.

**Comment by bkbilly** [comment]
You might be able to install the missing package like so:
```
sudo pip3 install pyalsaaudio
```
If it doesn't work, you will have to delete the `media.py` file and it's config from control and monitoring.

**Comment by Iceman248** [comment]
That worked, thanks. After doing that though and restarting service, I have the stats of cpu/memory and network download/upload in MQTT, but I don't see anything in HA. I don't see anything in the readme that made it clear to me the next step, but nothing shows up in HA.

**Comment by bkbilly** [comment]
I am happy that it worked!
For showing up on Home Assistant you need to make sure you have correctly configured the MQTT section from `config.yaml` and the `discovery->enabled` is `true`.
You should be able to see the new device on Home Assistant under the mqtt integration.

**Comment by Iceman248** [comment]
Okay, so after restarting some things it started working all of a sudden.

**Comment by Iceman248** [comment]
Is there an example of how to add the features that need additional setup, like notify? I see the thing at the bottom of the readme about adding python file in modules folder, but I couldn't make enough sense of that.

**Comment by bkbilly** [comment]
In order to send a notification from Home Assistant, you can do it like so:
```yaml
  - service: mqtt.publish
    data:
      topic: {prefix}/{clientId}/commands/notify
      payload: >-
        { "title": "My notification", "message": "my message" }
```
Now that you mention it, some info on README from the send-keys are not shown correctly, but you can read it from here:
https://raw.githubusercontent.com/bkbilly/lnxlink/master/README.md

As for the last section called Expanding is for programmers who want to add something that I don't currently support.

**Comment by Iceman248** [comment]
Thanks, figured that out, but I needed to be able to add an image to make it useful. I was trying to duplicate what I can do on Windows by having a notification sent from Frigate NVR of when it detects a person for example, it would show that image like I get on my phone as well.

**Comment by bkbilly** [comment]
Unfortunately linux notifications don't allow an image to be shown.

**Comment by bkbilly** [comment]
After some research I think that I found a way to show an image, but it is very small.

**Comment by Iceman248** [comment]
Thanks. What is very small?

**Comment by bkbilly** [comment]
I've just updated the notify service to show an icon from a URL or from a path from your PC.
It works like this:
```yaml
  - service: mqtt.publish
    data:
      topic: {prefix}/{clientId}/commands/notify
      payload: >-
        { "title": "My notification", "message": "my message" , "iconUrl": "http://myurl.com/image.png"}
```

**Comment by Iceman248** [comment]
Thanks. Better than no image. So there are no notifications whatsoever besides small icon that can be shown in Linux? I didn't really find anything either, but it seems like such an odd restriction from such an open and powerful OS.
