### ISSUE TITLE
Error with notifications: asynchronous calls

### ISSUE THREAD

**Issue by aqwserf** [bkbilly/lnxlink#48]
**Describe the problem**
With the recent update, I now have an error when receiving notification

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Version 2023.3.1

**Additional context**
Using MQTT to send a notification to my laptop, I never receive it. Instead, some errors appear in the logs.

I believe it was not the case with the previous release.

**Configuration**
Provide the configuration file, remove any sensitive info that might exist:
```yaml
mqtt:
  prefix: lnxlink
  clientId: bflap
  statsPrefix: monitor/stats
  server: xxx
  port: xxx
  auth:
    user: xxx
    pass: xxx
  discovery:
    enabled: true
  lwt:
    enabled: true
    qos: 1
    retain: true
    connectMsg: 'ON'
    disconnectMsg: 'OFF'
update_interval: 5
modules:
#- bash
#- bluetooth_battery
- camera_used
- cpu
#- disk_usage
- idle
- keep_alive
#- media
- memory
- microphone_used
- network_download
- network_upload
- notify
#- nvidia_gpu
- required_restart
#- restart
#- screen_onoff
#- send_keys
#- shutdown
#- suspend
- update
#- xdg_open                   
```

**Logs**
```txt
Mar 30 00:00:00 bflap lnxlink[718304]: Traceback (most recent call last):
Mar 30 00:00:00 bflap lnxlink[718304]:   File "/home/guik/.local/lib/python3.11/site-packages/lnxlink/__main__.py", line 163, in on_message
Mar 30 00:00:00 bflap lnxlink[718304]:     addon.startControl(select_service, message)
Mar 30 00:00:00 bflap lnxlink[718304]:   File "/home/guik/.local/lib/python3.11/site-packages/lnxlink/modules/notify.py", line 23, in startControl
Mar 30 00:00:00 bflap lnxlink[718304]:     notify2.init("Test")
Mar 30 00:00:00 bflap lnxlink[718304]:   File "/home/guik/.local/lib/python3.11/site-packages/notify2.py", line 111, in init
Mar 30 00:00:00 bflap lnxlink[718304]:     dbus_iface.connect_to_signal('ActionInvoked', _action_callback)
Mar 30 00:00:00 bflap lnxlink[718304]:   File "/usr/lib64/python3.11/site-packages/dbus/proxies.py", line 543, in connect_to_signal
Mar 30 00:00:00 bflap lnxlink[718304]:     return self._obj.connect_to_signal(signal_name, handler_function,
Mar 30 00:00:00 bflap lnxlink[718304]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 30 00:00:00 bflap lnxlink[718304]:   File "/usr/lib64/python3.11/site-packages/dbus/proxies.py", line 366, in connect_to_signal
Mar 30 00:00:00 bflap lnxlink[718304]:     self._bus.add_signal_receiver(handler_function,
Mar 30 00:00:00 bflap lnxlink[718304]:   File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 144, in add_signal_receiver
Mar 30 00:00:00 bflap lnxlink[718304]:     match = super(BusConnection, self).add_signal_receiver(
Mar 30 00:00:00 bflap lnxlink[718304]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 30 00:00:00 bflap lnxlink[718304]:   File "/usr/lib64/python3.11/site-packages/dbus/connection.py", line 388, in add_signal_receiver
Mar 30 00:00:00 bflap lnxlink[718304]:     self._require_main_loop()
Mar 30 00:00:00 bflap lnxlink[718304]: RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)
Mar 30 17:40:00 bflap lnxlink[718304]: Traceback (most recent call last):
Mar 30 17:40:00 bflap lnxlink[718304]:   File "/home/guik/.local/lib/python3.11/site-packages/lnxlink/__main__.py", line 163, in on_message
Mar 30 17:40:00 bflap lnxlink[718304]:     addon.startControl(select_service, message)
Mar 30 17:40:00 bflap lnxlink[718304]:   File "/home/guik/.local/lib/python3.11/site-packages/lnxlink/modules/notify.py", line 23, in startControl
Mar 30 17:40:00 bflap lnxlink[718304]:     notify2.init("Test")
Mar 30 17:40:00 bflap lnxlink[718304]:   File "/home/guik/.local/lib/python3.11/site-packages/notify2.py", line 111, in init
Mar 30 17:40:00 bflap lnxlink[718304]:     dbus_iface.connect_to_signal('ActionInvoked', _action_callback)
Mar 30 17:40:00 bflap lnxlink[718304]:   File "/usr/lib64/python3.11/site-packages/dbus/proxies.py", line 543, in connect_to_signal
Mar 30 17:40:00 bflap lnxlink[718304]:     return self._obj.connect_to_signal(signal_name, handler_function,
Mar 30 17:40:00 bflap lnxlink[718304]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 30 17:40:00 bflap lnxlink[718304]:   File "/usr/lib64/python3.11/site-packages/dbus/proxies.py", line 366, in connect_to_signal
Mar 30 17:40:00 bflap lnxlink[718304]:     self._bus.add_signal_receiver(handler_function,
Mar 30 17:40:00 bflap lnxlink[718304]:   File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 144, in add_signal_receiver
Mar 30 17:40:00 bflap lnxlink[718304]:     match = super(BusConnection, self).add_signal_receiver(
Mar 30 17:40:00 bflap lnxlink[718304]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 30 17:40:00 bflap lnxlink[718304]:   File "/usr/lib64/python3.11/site-packages/dbus/connection.py", line 388, in add_signal_receiver
Mar 30 17:40:00 bflap lnxlink[718304]:     self._require_main_loop()
Mar 30 17:40:00 bflap lnxlink[718304]: RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(.
```

**Comment by bkbilly** [comment]
The notification module uses an external package called notify2 so the 1st step is to test if it works on it's own.
Create a python script called `run_notify.py` containing this:
```python
import notify2

notify2.init("Test")
notify2.Notification(
    'Test notification',
    'Notification Message',
    'notification-message-im'
).show()
```
Run it with this command: 
```
python3 run_notify.py
```
If it doesn't work you can change the notify2 package version:
```
pip3 install -U notify2==0.3.1
```
and then retry running the above script.

Let me know if it works.

**Comment by aqwserf** [comment]
Thanks for your prompt response @bkbilly!

I confirm that it's working with your test script and my package is up-to-date:

```
pip freeze | grep -i notify 
notify2==0.3.1
pyinotify==0.9.6
```

**Comment by bkbilly** [comment]
I've had the same issue, but I never noticed it.
I'll try to fix it and I'll let you know.

**Comment by bkbilly** [comment]
I've pushed an update with the fix. You can try it by updating lnxlink to the latest version (2023.4.0) using this command:
```
pip3 install -U lnxlink
```

Let me know if you still have issues.

**Comment by aqwserf** [comment]
@bkbilly  I confirm this is working for me. Thanks for the quick fix!
