### ISSUE TITLE
Connection to MQTT via TLS with self-signed certificate fails

### ISSUE THREAD

**Issue by aqwserf** [bkbilly/lnxlink#73]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

Fedora 38

### Which version of LNXLink has the issue?

2023.10.0

### Describe the problem

After noticing that TLS connection is available, and as I already have Mosquito listening on port 8883 with a self-signed certificate, I tried to change `port: 8883` and `tls: true`, as see in #67 , LNXlink refuses to connect because it's a self-signed certificate.
Would it be possible to add a configuration to allow self-signed certificate?
Thanks!

### Configuration

```yaml
mqtt:
  prefix: lnxlink
  clientId: BFLap
  statsPrefix: monitor/stats
  server: ha.hysteresis.lan
  port: 1883
  auth:
    user: lnxlink
    pass: xxx
    tls: false
  discovery:
    enabled: true
  lwt:
    enabled: true
    qos: 1
    retain: true
    connectMsg: 'ON'
    disconnectMsg: 'OFF'
update_interval: 5
modules:
...
```

### Logs

```bash
/home/user/.config/lnxlink
INFO:lnxlink:LNXlink 2023.10.0 started: 3.11.5
INFO:lnxlink:Loaded addons: battery, camera_used, cpu, idle, inference_time, memory, notify, update, webcam
Traceback (most recent call last):
  File "/home/user/.local/bin/lnxlink", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/lnxlink/__main__.py", line 395, in main
    lnxlink = LNXlink(config_file)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/lnxlink/__main__.py", line 60, in __init__
    self.setup_mqtt()
  File "/home/user/.local/lib/python3.11/site-packages/lnxlink/__main__.py", line 150, in setup_mqtt
    self.client.connect(
  File "/home/user/.local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/lib64/python3.11/ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)
```

**Comment by bkbilly** [comment]
I've pushed an update that you can try by installing LNXlink as a developer.
Let me know if you still have issues.

**Comment by aqwserf** [comment]
I confirm this is working. Thanks for the quick patch @bkbilly!!
