### ISSUE TITLE
Won't launch due to ImportError: cannot import name GLib, introspection typelib not found

### ISSUE THREAD

**Issue by Baggypants** [bkbilly/lnxlink#80]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

Raspbian GNU/Linux 12 (bookworm)

### Which version of LNXLink has the issue?

lnxlink==2023.11.0 and git+https://github.com/bkbilly/lnxlink.git@6ff7452f9bb48c0d17a89cbb652d91019bc7595e#egg=lnxlink

### The problem

I'm trying to install lnxlink on Raspbian GNU/Linux 12 (bookworm). and I'm getting this issue

```bash
(venv) baggypants@raspberrypi:~/lnxlink-pip $ lnxlink -c config.yaml
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1074, in _find_spec
AttributeError: 'Importer' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/baggypants/lnxlink-pip/venv/bin/lnxlink", line 5, in <module>
    from lnxlink.__main__ import main
  File "/home/baggypants/lnxlink-pip/venv/lib/python3.11/site-packages/lnxlink/__main__.py", line 20, in <module>
    from .system_monitor import MonitorSuspend, GracefulKiller
  File "/home/baggypants/lnxlink-pip/venv/lib/python3.11/site-packages/lnxlink/system_monitor.py", line 11, in <module>
    from gi.repository import GLib
  File "/home/baggypants/lnxlink-pip/venv/lib/python3.11/site-packages/pgi/importer.py", line 157, in find_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name GLib, introspection typelib not found
```

```bash
(venv) baggypants@raspberrypi:~/lnxlink-pip $ python --version
Python 3.11.2
```
```bash
(venv) baggypants@raspberrypi:~/lnxlink-pip $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by bkbilly** [comment]
You should try installing the `gi` dependency manually, and try again.
```
sudo apt install libgirepository1.0-dev
pip install gi
```

**Comment by Baggypants** [comment]
Initially I followed the venv instructions from here https://bkbilly.gitbook.io/lnxlink/setup for Debian based distros

running `sudo apt install libgirepository1.0-dev; ` fixed it, thanks.

**Comment by bkbilly** [comment]
Awesome! I'll add it to the installation process.
