### ISSUE TITLE
Battery Entity unavailable

### ISSUE THREAD

**Issue by appleimperio** [bkbilly/lnxlink#82]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

Linux Mint 21.2 Cinnamon

### Which version of LNXLink has the issue?

lnxlink==2023.11.0

### Describe the problem

After making the installation the Battery entity is not avaivailable 
![Screenshot from 2023-11-17 15-43-02](https://github.com/bkbilly/lnxlink/assets/72883739/a7e72f2d-f0ac-4f4e-9ede-77894be468bc)
Verified with MQTT explorer and I can see the topic with the battery brand and percentage

### Additional context

In Home assistant i can see this error in the logs. I don't know if it's related.
```
2023-11-17 13:43:03.303 ERROR (MainThread) [homeassistant.components.mqtt.select] Invalid option for select.mint_pr_power_profile: '' (valid options: [])
```

### Configuration

```yaml
mqtt:
  prefix: lnxlink
  clientId: Mint-PR
  server: 192.168.0.202
  port: 1883
  auth:
    user: user
    pass: pas
    tls: false
  discovery:
    enabled: true
  lwt:
    enabled: true
    qos: 1
    retain: true
    connectMsg: 'ON'
    disconnectMsg: 'OFF'
update_interval: 5
modules: null
custom_modules: null
exclude:
- brightness
```

### Logs

```bash
Nov 17 11:08:36 Mint-MBP systemd[1041]: Started LNXlink.
Nov 17 11:08:36 Mint-MBP lnxlink[8563]: INFO:lnxlink:LNXlink 2023.11.0 started: 3.10.12
Nov 17 11:08:36 Mint-MBP lnxlink[8563]: INFO:lnxlink:Loaded addons: memory, webcam, xdg_open, sys_updates, send_keys, keep_alive, screenshot, bash, gpu, disk_usage, speech_recognition, cpu, power_profile, battery, inference_time, shutdown, microphone_used, idle, notify, suspend, camera_used, network, fullscreen, screen_onoff, update, media, audio_select, restart, required_restart, boot_select
Nov 17 11:08:36 Mint-MBP lnxlink[8563]: INFO:lnxlink:Connected to MQTT with code 0
Nov 17 11:10:22 Mint-MBP systemd[1041]: Stopping LNXlink...
Nov 17 11:10:22 Mint-MBP lnxlink[8563]: INFO:lnxlink:stopped gracefully
Nov 17 11:10:22 Mint-MBP lnxlink[8563]: INFO:lnxlink:Power Down detected.
Nov 17 11:10:22 Mint-MBP lnxlink[8563]: INFO:lnxlink:Disconnected from MQTT.
Nov 17 11:10:22 Mint-MBP lnxlink[8563]: /home/lrivera
Nov 17 11:10:23 Mint-MBP systemd[1041]: Stopped LNXlink.
Nov 17 11:10:23 Mint-MBP systemd[1041]: lnxlink.service: Consumed 6.539s CPU time.
Nov 17 11:10:23 Mint-MBP systemd[1041]: Started LNXlink.
Nov 17 11:10:23 Mint-MBP lnxlink[9344]: INFO:lnxlink:LNXlink 2023.11.0 started: 3.10.12
Nov 17 11:10:23 Mint-MBP lnxlink[9344]: INFO:lnxlink:Loaded addons: memory, webcam, xdg_open, sys_updates, send_keys, keep_alive, screenshot, bash, gpu, disk_usage, speech_recognition, cpu, power_profile, battery, inference_time, shutdown, microphone_used, idle, notify, suspend, camera_used, network, fullscreen, screen_onoff, update, media, audio_select, restart, required_restart, boot_select
Nov 17 11:10:23 Mint-MBP lnxlink[9344]: INFO:lnxlink:Connected to MQTT with code 0
Nov 17 11:10:45 Mint-MBP lnxlink[9344]: INFO:lnxlink:Message received webcam/webcam/: b'ON'
Nov 17 11:10:55 Mint-MBP lnxlink[9344]: INFO:lnxlink:Message received webcam/webcam/: b'OFF'
Nov 17 11:17:44 Mint-MBP systemd[1041]: Stopping LNXlink...
Nov 17 11:17:44 Mint-MBP lnxlink[9344]: INFO:lnxlink:stopped gracefully
Nov 17 11:17:44 Mint-MBP lnxlink[9344]: INFO:lnxlink:Power Down detected.
Nov 17 11:17:44 Mint-MBP lnxlink[9344]: INFO:lnxlink:Disconnected from MQTT.
Nov 17 11:17:44 Mint-MBP lnxlink[9344]: /home/lrivera
Nov 17 11:17:44 Mint-MBP systemd[1041]: Stopped LNXlink.
Nov 17 11:17:44 Mint-MBP systemd[1041]: lnxlink.service: Consumed 20.868s CPU time.
Nov 17 11:20:41 Mint-MBP systemd[1041]: Started LNXlink.
Nov 17 11:20:41 Mint-MBP lnxlink[13537]: INFO:lnxlink:LNXlink 2023.11.0 started: 3.10.12
Nov 17 11:20:41 Mint-MBP lnxlink[13537]: INFO:lnxlink:Loaded addons: memory, webcam, xdg_open, sys_updates, send_keys, keep_alive, screenshot, bash, gpu, disk_usage, speech_recognition, cpu, power_profile, battery, inference_time, shutdown, microphone_used, idle, notify, suspend, camera_used, network, fullscreen, screen_onoff, update, media, audio_select, restart, required_restart, boot_select
Nov 17 11:20:41 Mint-MBP lnxlink[13537]: INFO:lnxlink:Connected to MQTT with code 0
Nov 17 11:24:01 Mint-MBP lnxlink[13537]: INFO:lnxlink:Message received restart/restart/: b'PRESS'
Nov 17 11:24:01 Mint-MBP lnxlink[13537]: INFO:lnxlink:Power Down detected.
Nov 17 11:24:01 Mint-MBP lnxlink[13537]: INFO:lnxlink:Power Down detected.
Nov 17 11:24:01 Mint-MBP lnxlink[13537]: INFO:lnxlink:stopped gracefully
Nov 17 11:24:01 Mint-MBP lnxlink[13537]: INFO:lnxlink:Power Down detected.
Nov 17 11:24:01 Mint-MBP systemd[1041]: Stopping LNXlink...
Nov 17 11:24:01 Mint-MBP systemd[1041]: lnxlink.service: Main process exited, code=exited, status=1/FAILURE
Nov 17 11:24:01 Mint-MBP systemd[1041]: lnxlink.service: Failed with result 'exit-code'.
Nov 17 11:24:01 Mint-MBP systemd[1041]: Stopped LNXlink.
Nov 17 11:24:01 Mint-MBP systemd[1041]: lnxlink.service: Consumed 10.333s CPU time.
-- Boot a5480dd16ef141a7aa5cfe7ec6ba59fc --
Nov 17 11:24:30 Mint-MBP systemd[1043]: Started LNXlink.
Nov 17 11:24:31 Mint-MBP lnxlink[1051]: INFO:lnxlink:LNXlink 2023.11.0 started: 3.10.12
Nov 17 11:24:31 Mint-MBP lnxlink[1051]: INFO:lnxlink:Loaded addons: memory, webcam, xdg_open, sys_updates, send_keys, keep_alive, screenshot, bash, gpu, disk_usage, speech_recognition, cpu, power_profile, battery, inference_time, shutdown, microphone_used, idle, notify, suspend, camera_used, network, fullscreen, screen_onoff, update, media, audio_select, restart, required_restart, boot_select
Nov 17 11:24:31 Mint-MBP lnxlink[1051]: INFO:lnxlink:Connected to MQTT with code 0
Nov 17 11:24:32 Mint-MBP lnxlink[1051]: ERROR:lnxlink:Error with addon Idle: [Errno 2] No such file or directory: 'xprintidle', Traceback (most recent call last):
Nov 17 11:24:32 Mint-MBP lnxlink[1051]:   File "/home/lrivera/lnxlink_venv/lib/python3.10/site-packages/lnxlink/__main__.py", line 96, in run_modules
Nov 17 11:24:32 Mint-MBP lnxlink[1051]:     pub_data = method["method"]()
Nov 17 11:24:32 Mint-MBP lnxlink[1051]:   File "/home/lrivera/lnxlink_venv/lib/python3.10/site-packages/lnxlink/modules/idle.py", line 18, in get_info
Nov 17 11:24:32 Mint-MBP lnxlink[1051]:     idle_ms = monitor.get_dbus_idle()
Nov 17 11:24:32 Mint-MBP lnxlink[1051]:   File "/home/lrivera/lnxlink_venv/lib/python3.10/site-packages/dbus_idle/__init__.py", line 100, in get_dbus_idle
Nov 17 11:24:32 Mint-MBP lnxlink[1051]:     stdout = subprocess.run(
Nov 17 11:24:32 Mint-MBP lnxlink[1051]:   File "/usr/lib/python3.10/subprocess.py", line 503, in run
Nov 17 11:24:32 Mint-MBP lnxlink[1051]:     with Popen(*popenargs, **kwargs) as process:
Nov 17 11:24:32 Mint-MBP lnxlink[1051]:   File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
Nov 17 11:24:32 Mint-MBP lnxlink[1051]:     self._execute_child(args, executable, preexec_fn, close_fds,
Nov 17 11:24:32 Mint-MBP lnxlink[1051]:   File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
Nov 17 11:24:32 Mint-MBP lnxlink[1051]:     raise child_exception_type(errno_num, err_msg, err_filename)
Nov 17 11:24:32 Mint-MBP lnxlink[1051]: FileNotFoundError: [Errno 2] No such file or directory: 'xprintidle'
Nov 17 11:24:33 Mint-MBP lnxlink[1051]: ERROR:lnxlink:Error with addon Fullscreen: 'NoneType' object is not iterable, Traceback (most recent call last):
Nov 17 11:24:33 Mint-MBP lnxlink[1051]:   File "/home/lrivera/lnxlink_venv/lib/python3.10/site-packages/lnxlink/__main__.py", line 96, in run_modules
Nov 17 11:24:33 Mint-MBP lnxlink[1051]:     pub_data = method["method"]()
Nov 17 11:24:33 Mint-MBP lnxlink[1051]:   File "/home/lrivera/lnxlink_venv/lib/python3.10/site-packages/lnxlink/modules/fullscreen.py", line 29, in get_info
Nov 17 11:24:33 Mint-MBP lnxlink[1051]:     windows = ewmh.getClientList()
Nov 17 11:24:33 Mint-MBP lnxlink[1051]:   File "/home/lrivera/lnxlink_venv/lib/python3.10/site-packages/ewmh/ewmh.py", line 248, in getClientList
Nov 17 11:24:33 Mint-MBP lnxlink[1051]:     return [self._createWindow(w)
Nov 17 11:24:33 Mint-MBP lnxlink[1051]: TypeError: 'NoneType' object is not iterable
```

**Comment by bkbilly** [comment]
It seems that the LNXlink service keeps crashing, so that's the reason why the battery sensor is unavailable. This is due to some modules not supported by your OS, so they need to be excluded.

Based on your logs, I can see issues with the following modules:

## power_profile
Based on the Home Assistant logs the power is not supported, so you might want to exclude it. This is the result from this command `powerprofilesctl list`.
If it returns something please write the result to fix this module.

## idle
There seems to be an issue with the idle module which is using the `xprintidle` as a backup command to get the idle time. You can try installing this, but if the issue is not fixed you will have to exclude this too.
On Ubuntu the command is `sudo apt install xprintidle`, but I am not sure for Linux Mint.

## fullscreen
It seems that there is an issue with the fullscreen module, so most likely you will have to exclude this too.

**Comment by appleimperio** [comment]
@bkbilly Thank you no more error in the logs after installing the software you suggest and after running the powerprofile command it suggest to install another one and adding fullscreen to the exceptions. But the most important for me which is the battery is still not available. I want to create an automation that charge the laptop battery when is lower than 30% and when it get to 100% turn off the charger. I look on the issues and this is not the first time the battery entity is not showing the other time the guy fix the problem extracting the value with node red but i still haven't use node red. Any idea if this could be fixed or since I can see the topic with the value how to add it to home assistant manually? Thank you

**Comment by bkbilly** [comment]
I think I know what is the issue... 
You will have to enable the sensor on home assistant because by default it's not enabled.

**Comment by appleimperio** [comment]
Thank you, thank you!!!

**Comment by bkbilly** [comment]
On the dev installation type, I've changed the behaviour of how battery sensors are created.
A new sensor is created for each battery device found on the system with a unique name.
If a new device is connected, it will automatically show up as a new sensor.

This will be on the next release and it will break any automations you might have created, but it's necessary for these new features to work.
